/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../Mux2x1_Estructural_Sintetizado.v:1" *)
module Mux2x1_Estructural_Sintetizado(dataOut, dataIn0, dataIn1, selector, clk, reset);
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  wire [1:0] _00_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  wire _01_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  wire _02_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:3" *)
  wire _03_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:3" *)
  wire _04_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:4" *)
  wire _05_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:4" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:7" *)
  wire _15_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:5" *)
  wire _16_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:6" *)
  input clk;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:3" *)
  input [1:0] dataIn0;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:4" *)
  input [1:0] dataIn1;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:2" *)
  output [1:0] dataOut;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:9" *)
  wire [1:0] out;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:7" *)
  input reset;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:5" *)
  input selector;
  NOT _17_ (
    .A(_05_),
    .Y(_14_)
  );
  NOT _18_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _19_ (
    .A(_16_),
    .B(_04_),
    .Y(_08_)
  );
  NAND _20_ (
    .A(_16_),
    .B(_07_),
    .Y(_09_)
  );
  NAND _21_ (
    .A(_15_),
    .B(_09_),
    .Y(_10_)
  );
  NOR _22_ (
    .A(_08_),
    .B(_10_),
    .Y(_02_)
  );
  NOR _23_ (
    .A(_03_),
    .B(_16_),
    .Y(_11_)
  );
  NAND _24_ (
    .A(_14_),
    .B(_16_),
    .Y(_12_)
  );
  NAND _25_ (
    .A(_15_),
    .B(_12_),
    .Y(_13_)
  );
  NOR _26_ (
    .A(_11_),
    .B(_13_),
    .Y(_01_)
  );
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  DFF _27_ (
    .C(clk),
    .D(_00_[0]),
    .Q(dataOut[0])
  );
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  DFF _28_ (
    .C(clk),
    .D(_00_[1]),
    .Q(dataOut[1])
  );
  assign _15_ = reset;
  assign _00_[1] = _02_;
  assign _03_ = dataIn0[0];
  assign _05_ = dataIn1[0];
  assign _16_ = selector;
  assign _04_ = dataIn0[1];
  assign _06_ = dataIn1[1];
  assign _00_[0] = _01_;
endmodule
