/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../Mux2x1_Estructural_Sintetizado.v:1" *)
module Mux2x1_Estructural_Sintetizado(dataOut, dataIn0, dataIn1, selector, clk, reset);
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  wire [1:0] _0_;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:6" *)
  input clk;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:3" *)
  input [1:0] dataIn0;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:4" *)
  input [1:0] dataIn1;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:2" *)
  output [1:0] dataOut;
  reg [1:0] dataOut;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:9" *)
  wire [1:0] out;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:7" *)
  input reset;
  (* src = "../Mux2x1_Estructural_Sintetizado.v:5" *)
  input selector;
  assign _0_[0] = reset ? (* src = "../Mux2x1_Estructural_Sintetizado.v:22" *) out[0] : 1'h0;
  assign _0_[1] = reset ? (* src = "../Mux2x1_Estructural_Sintetizado.v:22" *) out[1] : 1'h0;
  assign out[0] = selector ? (* src = "../Mux2x1_Estructural_Sintetizado.v:14" *) dataIn1[0] : dataIn0[0];
  assign out[1] = selector ? (* src = "../Mux2x1_Estructural_Sintetizado.v:14" *) dataIn1[1] : dataIn0[1];
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  always @(posedge clk)
      dataOut[0] <= _0_[0];
  (* src = "../Mux2x1_Estructural_Sintetizado.v:20" *)
  always @(posedge clk)
      dataOut[1] <= _0_[1];
endmodule
